routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('logout', 'Auth\LoginController@logout');
Auth::routes();


Route::get('admin/login', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\LoginController@login')->name('admin.login');
Route::get('admin/logout', 'Admin\LoginController@logout')->name('admin.logout');


Route::group(['middleware' => ['auth']], function () {
		Route::get('/', 'HomeController@index')->name('home');
		Route::get('restaurants','Front\RestaurantController@getRestaurantList')->name('restaurant.list');
		Route::get('restaurant/{id}/info','Front\RestaurantController@getRestaurantInfo')->name('restaurant.info');
		Route::get('restaurant/{id}/info/location','Front\RestaurantController@getRestaurantLocation')->name('restaurant.info.location');
		Route::get('restaurant/{id}/info/review','Front\RestaurantController@createComment')->name('restaurant.info.comment');
		Route::post('restaurant/{id}/info/review','Front\RestaurantController@storeComment')->name('store.comment');

		
		});

		
	
Route::group(['prefix' => 'admin', 'middleware' => ['admin'], 'as' => 'admin.' ], function () {
		Route::get('/','Admin\DashboardController@index')->name('dashboard');
		Route::put('restaurant-restore/{id}','Admin\RestaurantController@rest')->name('restaurants.restore');
		Route::get('restaurants/archive','Admin\RestaurantController@archive')->name('restaurants.archive');
		Route::resource('restaurants','Admin\RestaurantController');
		Route::get('/users/delete/{id}','Admin\UserController@delete')->name('users.delete');
		Route::resource('users','Admin\UserController');
		Route::resource('logs','Admin\LogController');

});

app/Http/Controllers/Owner/DashboardController.php
<?php

namespace App\Http\Controllers\Owner;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
        return view('owner.dashboard');
    }
}

resources/views/layouts/owner/app.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Korean Restaurant Locator AdminPanel</title>

    <!-- Bootstrap -->
    <link href="{{ asset('gentelella/vendors/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
    <!-- Font Awesome -->
    <link href="{{ asset('gentelella/vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <!-- NProgress -->
    <link href="{{ asset('gentelella/vendors/nprogress/nprogress.css') }}" rel="stylesheet" type="text/css">

    <link href="{{ asset('gentelella/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css') }}" rel="stylesheet" type="text/css">
    <!-- bootstrap-daterangepicker -->
    <link href="{{ asset('gentelella/vendors/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{{ asset('gentelella/build/css/custom.min.css') }}" rel="stylesheet" type="text/css">
    <!-- Datatables css -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.25.0/codemirror.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.6.0/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.6.0/css/froala_style.min.css" rel="stylesheet" type="text/css" />
    

     <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
    

  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        @include('layouts.owner.sidebar')

        <!-- top navigation -->
        @include('layouts.owner.header')
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
           @yield('content')
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        @include('layouts.owner.footer')
        <!-- /footer content -->
      </div>
    </div>
    <!-- Sweet Alert -->
    <script type="text/javascript" src="{{asset('gentelella/js/sweetalert.js')}}"></script>
    <!-- jQuery -->
    <script type="text/javascript" src="{{ asset('gentelella/vendors/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap -->
    <script type="text/javascript" src="{{ asset('gentelella/vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <!-- FastClick -->
    <script type="text/javascript" src="{{ asset('gentelella/vendors/fastclick/lib/fastclick.js') }}"></script>
    <!-- NProgress -->
    <script type="text/javascript" src="{{ asset('gentelella/vendors/nprogress/nprogress.js') }}"></script>
    
    <!-- Custom Theme Scripts -->
    <script type="text/javascript" src="{{ asset('gentelella/build/js/custom.min.js') }}"></script>

    <!-- Chart.js -->
    <script type="text/javascript" src="{{ asset('gentelella/vendors/Chart.js/dist/Chart.min.js') }}"></script>
    <!-- jQuery Sparklines -->
    <script type="text/javascript" src="{{ asset('gentelella/vendors/jquery-sparkline/dist/jquery.sparkline.min.js') }}"></script>
    <!-- morris.js -->
    <script type="text/javascript" src="{{ asset('gentelella/vendors/raphael/raphael.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('gentelella/vendors/morris.js/morris.min.js') }}"></script>
    <!-- gauge.js -->
    <script type="text/javascript" src="{{ asset('gentelella/vendors/gauge.js/dist/gauge.min.js') }}"></script>
    <!-- bootstrap-progressbar -->
    <script type="text/javascript" src="{{ asset('gentelella/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script>
    <!-- Skycons -->
    <script type="text/javascript" src="{{ asset('gentelella/vendors/skycons/skycons.js') }}"></script>
    <!-- Flot -->
    <script type="text/javascript" src="{{ asset('gentelella/vendors/Flot/jquery.flot.js') }}"></script>
    <script type="text/javascript" src="{{ asset('gentelella/vendors/Flot/jquery.flot.pie.js') }}"></script>
    <script type="text/javascript" src="{{ asset('gentelella/vendors/Flot/jquery.flot.time.js') }}"></script>
    <script type="text/javascript" src="{{ asset('gentelella/vendors/Flot/jquery.flot.stack.js') }}"></script>
    <script type="text/javascript" src="{{ asset('gentelella/vendors/Flot/jquery.flot.resize.js') }}"></script>
    <!-- Flot vendors -->
    <script type="text/javascript" src="{{ asset('gentelella/vendors/flot.orderbars/js/jquery.flot.orderBars.js') }}"></script>
    <script type="text/javascript" src="{{ asset('gentelella/vendors/flot-spline/js/jquery.flot.spline.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('gentelella/vendors/flot.curvedlines/curvedLines.js') }}"></script>
    <!-- DateJS -->
    <script type="text/javascript" src="{{ asset('gentelella/vendors/DateJS/build/date.js') }}"></script>
    <!-- bootstrap-daterangepicker -->
    <script type="text/javascript" src="{{ asset('gentelella/vendors/moment/min/moment.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('gentelella/vendors/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript" src="{{asset('gentelella/vendors/validator/validator.js')}}"></script>

    <script type="text/javascript" src="{{ asset('vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
    <script>
    CKEDITOR.replace( 'about' );
    </script>
  

    <script type="text/javascript">$(document).ready(function(){
    $('#productsample').DataTable();
    $('#categorysample').DataTable();
    });
    // modal
    <!-- Dialog show event handler -->
  $('#confirmDelete').on('show.bs.modal', function (e) {
      $message = $(e.relatedTarget).attr('data-message');
      $(this).find('.modal-body p').text($message);
      $title = $(e.relatedTarget).attr('data-title');
      $(this).find('.modal-title').text($title);

      // Pass form reference to modal for submission on yes/ok
      var form = $(e.relatedTarget).closest('form');
      $(this).find('.modal-footer #confirm').data('form', form);
  });

  <!-- Form confirm (yes/ok) handler, submits form -->
  $('#confirmDelete').find('.modal-footer #confirm').on('click', function(){
      $(this).data('form').submit();
  });


    </script>
    
    

  </body>
</html>

resources/views/layouts/owner/footer.blade.php
<footer class="footer_fixed">
    <div class="pull-right">

    </div>
    <div class="clearfix"></div>
</footer>

resources/views/layouts/owner/header.blade.php
<div class="top_nav">
    <div class="nav_menu">
        <nav>
        <div class="nav toggle">
            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>

        <ul class="nav navbar-nav navbar-right">
            <li class="">
            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                {{ $user->name }}
                <img src="{{asset('gentelella/production/images/img.jpg') }}" alt="">
                <span class=" fa fa-angle-down"></span>
            </a>
            <ul class="dropdown-menu dropdown-usermenu pull-right">
                <li><a href="javascript:;"> Profile</a></li>
                <li>
                <a href="javascript:;">
                    <span class="badge bg-red pull-right">50%</span>
                    <span>Settings</span>
                </a>
                </li>
                <li>
                <a href="javascript:;">Help</a>
                </li>
                <li>
                <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-sign-out pull-right"></i>Logout
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </li>
            </ul>
            </li>

            
        </ul>
        </nav>
    </div>
</div>

resources/views/layouts/owner/sidebar.blade.php
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
        <a href="{{url('/admin')}}" class="site_title"><i class="fa fa-paw"></i> <span>KRL</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
        <div class="profile_pic">
            <img src="{{ asset('gentelella/production/images/img.jpg') }}" alt="..." class="img-circle profile_img">
        </div>
        <div class="profile_info">
            <span>Welcome, 
            <br>{{ $user->name }}
            <h2></h2>
        </div>
        <div class="clearfix"></div>
        </div>
        <!-- /menu profile quick info -->

        <br />
        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
        <div class="menu_section">
            <h3>General</h3>
            <ul class="nav side-menu">
            <li><a><i class="fa fa-product-hunt"></i> Restaurants <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                <li><a href="#">List of Restaurants</a></li>
                </ul>
            </li>
            </ul>
        </div>
        <div class="menu_section">
            <h3>Others</h3>
            <ul class="nav side-menu">
            <li><a><i class="fa fa-archive"></i> Archive <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                <li><a href="{{route('owner.restaurants.archive')}}">Restaurants</a></li>
                </ul>
            </li>
            <li><a href="{{route('owner.logs.index')}}"><i class="fa fa-history"></i> Logs</a>
            </li>
            </li>            
            </ul>
        </div>

        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
        <a data-toggle="tooltip" data-placement="top" title="Settings">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="FullScreen">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Lock">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
        </a>
        <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
        </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>