routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('logout', 'Auth\LoginController@logout');
Auth::routes();


Route::get('admin/login', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\LoginController@login')->name('admin.login');
Route::get('admin/logout', 'Admin\LoginController@logout')->name('admin.logout');


Route::group(['middleware' => ['auth']], function () {
		Route::get('/', 'HomeController@index')->name('home');
		Route::get('restaurants','Front\RestaurantController@getRestaurantList')->name('restaurant.list');
		Route::get('restaurant/{id}/info','Front\RestaurantController@getRestaurantInfo')->name('restaurant.info');
		Route::get('restaurant/{id}/info/location','Front\RestaurantController@getRestaurantLocation')->name('restaurant.info.location');
		Route::get('restaurant/{id}/info/review','Front\RestaurantController@createComment')->name('restaurant.info.comment');
		Route::post('restaurant/{id}/info/review','Front\RestaurantController@storeComment')->name('store.comment');

		
		});

		
	
Route::group(['prefix' => 'admin', 'middleware' => ['admin'], 'as' => 'admin.' ], function () {
		Route::get('/','Admin\DashboardController@index')->name('dashboard');
		Route::put('restaurant-restore/{id}','Admin\RestaurantController@rest')->name('restaurants.restore');
		Route::get('restaurants/archive','Admin\RestaurantController@archive')->name('restaurants.archive');
		Route::resource('restaurants','Admin\RestaurantController');
		Route::get('/users/delete/{id}','Admin\UserController@delete')->name('users.delete');
		Route::resource('users','Admin\UserController');
		Route::resource('logs','Admin\LogController');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Models\Restaurant;
class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'role',
        'firstName',
        'middleName',
        'lastName',
        'email',
        'password'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function restaurants()
    {
        return $this->hasMany(Restaurant::class);
    }


    public function getFullNameAttribute()
    {
        return "{$this->firstName} {$this->middleName} {$this->lastName}";
    }
    public function getRoleAttribute($value)
    {
        return ucfirst($value);
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
class UserController extends Controller
{
    private $user;


    public function __construct(User $user)
    {
        $this->user = $user;
    }

    public function index()
    {   
        $users = $this->user->get();

        return view('admin.users.index',[
            'users' => $users
        ]);
    }


    public function create()
    {
        return view(admin.users.create);
    }


    public function store(Request $request)
    {
        $this->user->create($request->all());
        
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        return view('admin.users.edit',[
            'user' => $this->user->findOrfail($id)
        ]);
    }


    public function update(Request $request, $id)
    {
        //
    }


    public function delete($id)
    {
        $this->user->findOrFail($id)->delete();
        return redirect('/admin/users')->with('alert-type', 'success')
        ->with('alert-message', 'Successfully deleted');
    }
}

resources/views/admin/users/index.blade.php
@extends('layouts.admin.app')
@section('content')
  @include('layouts.modal')
        <div class="clearfix"></div>
                @include('partials.alert-messages')
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>User <small>Users</small></h2>

                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <div class="table-responsive">
 
                        <table class="table">
                            <thead>
                                <th class="col-md-2">Fullname</th>
                                <th class="col-md-2">Role</th>
                                <th class="col-md-2">Email</th>
                                <th class="col-md-2">Action</th>
                            </thead>
                        <tbody>
                        @foreach ($users as $user)
                        <tr>
                            <td><a href="{{route('admin.users.show',$user->id)}}">{{ $user->fullName }}</a></td>
                            <td>{{ $user->role }}</td>
                            <td>{{ $user->email }}</td>
                            <td>
                                <a class="dropdown-item" href="{{ route('admin.users.edit',$user->id) }}">Update</a>
                                <a class="dropdown-item" href="{{ route('admin.users.delete',$user->id) }}">Delete</a>            
                            </td>
                        </tr>
                        @endforeach
                        </tbody>
                        </table>
                    </div>
                            
                        
                  </div>
                </div>
              </div>
@endsection