routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('logout', 'Auth\LoginController@logout');
Auth::routes();


Route::get('admin/login', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Admin\LoginController@login')->name('admin.login');
Route::get('admin/logout', 'Admin\LoginController@logout')->name('admin.logout');


Route::group(['middleware' => ['auth']], function () {
		Route::get('/', 'HomeController@index')->name('home');
		Route::get('restaurants','Front\RestaurantController@getRestaurantList')->name('restaurant.list');
		Route::get('restaurant/{id}/info','Front\RestaurantController@getRestaurantInfo')->name('restaurant.info');
		Route::get('restaurant/{id}/info/location','Front\RestaurantController@getRestaurantLocation')->name('restaurant.info.location');
		Route::get('restaurant/{id}/info/review','Front\RestaurantController@createComment')->name('restaurant.info.comment');
		Route::post('restaurant/{id}/info/review','Front\RestaurantController@storeComment')->name('store.comment');

		
		});

		
	
Route::group(['prefix' => 'admin', 'middleware' => ['admin'], 'as' => 'admin.' ], function () {
		Route::get('/','Admin\DashboardController@index')->name('dashboard');
		Route::put('restaurant-restore/{id}','Admin\RestaurantController@rest')->name('restaurants.restore');
		Route::get('restaurants/archive','Admin\RestaurantController@archive')->name('restaurants.archive');
		Route::resource('restaurants','Admin\RestaurantController');
		Route::get('/users/delete/{id}','Admin\UserController@delete')->name('users.delete');
		Route::resource('users','Admin\UserController');
		Route::resource('logs','Admin\LogController');

});

resources/views/layouts/admin/app.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Korean Restaurant Locator AdminPanel</title>

    @include('partials.admin.css-files')

     <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
    

  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        @include('layouts.admin.sidebar')

        <!-- top navigation -->
        @include('layouts.admin.header')
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
           @yield('content')
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        @include('layouts.admin.footer')
        <!-- /footer content -->
      </div>
    </div>
    @include('partials.admin.js-files')
    <script>
    CKEDITOR.replace( 'about' );
    </script>
  

    <script type="text/javascript">$(document).ready(function(){
    $('#productsample').DataTable();
    $('#categorysample').DataTable();
    });
    // modal
    <!-- Dialog show event handler -->
  $('#confirmDelete').on('show.bs.modal', function (e) {
      $message = $(e.relatedTarget).attr('data-message');
      $(this).find('.modal-body p').text($message);
      $title = $(e.relatedTarget).attr('data-title');
      $(this).find('.modal-title').text($title);

      // Pass form reference to modal for submission on yes/ok
      var form = $(e.relatedTarget).closest('form');
      $(this).find('.modal-footer #confirm').data('form', form);
  });

  <!-- Form confirm (yes/ok) handler, submits form -->
  $('#confirmDelete').find('.modal-footer #confirm').on('click', function(){
      $(this).data('form').submit();
  });


    </script>
    
    

  </body>
</html>

resources/views/layouts/admin/footer.blade.php
<footer class="footer_fixed">
  <div class="pull-right">

  </div>
  <div class="clearfix"></div>
</footer>

resources/views/layouts/admin/header.blade.php
<div class="top_nav">
    <div class="nav_menu">
      <nav>
        <div class="nav toggle">
          <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>

        <ul class="nav navbar-nav navbar-right">
          <li class="">
            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
              {{ $user->name }}
              <img src="{{asset('gentelella/production/images/img.jpg') }}" alt="">
              <span class=" fa fa-angle-down"></span>
            </a>
            <ul class="dropdown-menu dropdown-usermenu pull-right">
              <li><a href="javascript:;"> Profile</a></li>
              <li>
                <a href="javascript:;">
                  <span class="badge bg-red pull-right">50%</span>
                  <span>Settings</span>
                </a>
              </li>
              <li>
                <a href="javascript:;">Help</a>
              </li>
              <li>
              <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-sign-out pull-right"></i>Logout
              </a>

              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  {{ csrf_field() }}
              </form>
            </li>
            </ul>
          </li>

          
        </ul>
      </nav>
    </div>
  </div>

resources/views/layouts/admin/sidebar.blade.php
<div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="{{url('/admin')}}" class="site_title"><i class="fa fa-paw"></i> <span>KRL</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="{{ asset('gentelella/production/images/img.jpg') }}" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome, 
                  <br>{{ $user->name }}
                <h2></h2>
              </div>
              <div class="clearfix"></div>
            </div>
            <!-- /menu profile quick info -->

            <br />
            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-product-hunt"></i> Restaurants <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{{route('admin.restaurants.index')}}">List of Restaurants</a></li>
                    </ul>
                    <li><a href="{{route('admin.users.index')}}"><i class="fa fa-users"></i>Users</a>
                  </li>
                </ul>
              </div>
              <div class="menu_section">
                <h3>Others</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-archive"></i> Archive <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{{route('admin.restaurants.archive')}}">Restaurants</a></li>
                    </ul>
                  </li>
                  <li><a href="{{route('admin.logs.index')}}"><i class="fa fa-history"></i> Logs</a>
                  </li>
                  </li>            
                </ul>
              </div>

            </div>
            <!-- /sidebar menu -->

            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>